services:
  cutan:
    build:
      context: /env
    ports:
      - "8000:8000"
    volumes:
      - ./env/cutan:/cutan
    environment:
      - DB_HOST=database
      - DB_NAME=cutandb
      - DB_USER=dbuser
      - DB_PASS=pass
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database

  database:
    image: postgres:16.0-alpine3.17
    environment:
      - POSTGRES_DB=cutandb
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass